version: '3.8'

services:
  server:
    build:
      context: .  # Current directory where this file is located
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - FLASK_APP=app.py
    depends_on:
      - db
    volumes:
      - .:/app  # Mount the current directory to /app in the container

  scrapy:
    build:
      context: ./scraper  # The scraper directory
    depends_on:
      - db
    volumes:
      - ./scraper:/usr/src/app  # Mount the scraper directory to /usr/src/app in the container

  db:
    image: postgres
    restart: always
    user: postgres
    environment:
      - POSTGRES_DB=example
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
      - db-data:/var/lib/postgresql/data
    secrets:
      - db-password
    expose:
      - "5432"
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:

secrets:
  db-password:
    file: ./db/password.txt  # The file is located in the db directory
